{% set name = "datafusion" %}
{% set version = "28.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c40d2b79754a3e051d0c5b00827d7ed32cdb5cf78d26b0738e631dcd63160209


build:
  number: 0
  skip: true  # [win]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin >=0.15,<0.16
    - libprotobuf =3
  host:
    - python
    - maturin >=0.15,<0.16
    - pip
  run:
    - python
    - pyarrow >=11.0.0

test:
  imports:
    - datafusion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://arrow.apache.org/datafusion
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: Extensible query execution framework
  description: |
    DataFusion is an extensible query execution framework, written in Rust,
    that uses Apache Arrow as its in-memory format.
  doc_url: https://arrow.apache.org/datafusion
  dev_url: https://github.com/apache/arrow-datafusion

extra:
  recipe-maintainers:
    - cpcloud
    - andygrove
    - charlesbluca
